-- =============================================================================
-- QUERY HISTORY — 60 realistic enterprise queries (6 per domain)
-- =============================================================================
INSERT INTO query_history (
  session_id, query, task_category, task_type, routing_plan,
  slm_used, response_summary, hallucination_rate, task_completion_rate,
  latency_ms, token_count_in, token_count_out, created_at
) VALUES

-- ── SUPPLY CHAIN (6 queries) ─────────────────────────────────────────────────
('sess-sc-001',
 'What is the projected impact of a 25% US tariff on Chinese electronics components on our Q3 procurement costs, and which alternative suppliers in Vietnam or Mexico can absorb the shortfall within 8 weeks?',
 'DOMAIN','analysis',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3","llama3:8b"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'A 25% tariff increase would add approximately $4.2M to Q3 procurement costs across 14 affected SKU families. Three qualified Vietnamese suppliers (Vinatex Electronics, HCM Components Ltd, Saigon Tech Parts) have confirmed capacity and can onboard within 6–8 weeks via existing supplier agreements. Mexican alternative Monterrey Industrial has a 3-week lead time but requires a new vendor qualification audit.',
 0.031, 0.956, 2847, 412, 687, NOW() - INTERVAL '40 days'),

('sess-sc-001',
 'Generate a freight re-routing plan for our European distribution network assuming Rotterdam port is closed for 3 weeks due to strike action, prioritising pharmaceutical SKUs.',
 'DOMAIN','planning',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'Primary re-route: Hamburg (DE) and Felixstowe (UK) absorb 68% of Rotterdam volume. Pharmaceutical cold-chain SKUs (Priority A) rerouted via Antwerp air-freight corridor at +€1.8M incremental cost. Ambient SKUs shifted to Hamburg rail connectors. Estimated full recovery within 19 days. Seven 3PL partners notified with revised SLAs.',
 0.028, 0.971, 3124, 388, 742, NOW() - INTERVAL '35 days'),

('sess-sc-001',
 'Identify the top 10 single-source suppliers in our Tier 1 network where a disruption would halt more than 15% of production output, and recommend dual-sourcing options.',
 'DOMAIN','risk_assessment',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3","gemma3"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'Identified 10 critical single-source dependencies: SemiCore (IC substrates, 23% prod exposure), Nexus Plastics (injection-moulded housings, 19%), FlexSeal GmbH (industrial seals, 17%)—and 7 others. Dual-source programmes recommended with 6–18 month qualification timelines. Immediate risk mitigation: increase safety stock for top 3 to 12-week cover (current: 4 weeks).',
 0.041, 0.942, 3891, 467, 821, NOW() - INTERVAL '28 days'),

('sess-sc-001',
 'What does our demand forecast look like for SKU category FMCG-HPC-022 through Q4, accounting for back-to-school seasonality and the planned promotional campaign in September?',
 'DOMAIN','forecasting',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'Q4 forecast for FMCG-HPC-022: July 1.2M units (baseline), August 1.4M (+17% back-to-school uplift), September 1.9M (+58% including 6-week promotional campaign), October 1.1M (post-promo trough), November 1.6M (+Q4 seasonal ramp). Recommend pre-building 800K units in June/July to buffer against September demand spike. 3PL warehouse expansion at DC-Birmingham flagged as constraint.',
 0.038, 0.948, 2673, 341, 614, NOW() - INTERVAL '20 days'),

('sess-sc-001',
 'Analyse our 3PL partner performance scorecards for the last 6 months. Which carriers are underperforming on OTIF and what contractual remedies are available?',
 'DOMAIN','performance_review',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'Three carriers below contractual 95% OTIF threshold: FastFreight UK (88.3%, -6.7pp), Nordic Express (91.2%, -3.8pp), TranzCargo Iberia (89.7%, -5.3pp). Per Schedule 3 of the Master Logistics Agreement, performance credits of 1.5% of monthly freight spend apply for each percentage point below 95%. Estimated Q2 credit: £287K. Service Improvement Plans required within 14 days per clause 18.4.',
 0.033, 0.961, 2284, 298, 571, NOW() - INTERVAL '10 days'),

('sess-sc-001',
 'Build an inventory optimisation model recommendation for our 12 highest-velocity SKUs to reduce working capital by 18% while maintaining a 99.2% service level.',
 'DOMAIN','optimisation',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-supply-chain-v3","llama3:8b"]}'::jsonb,
 'dhs-slm-supply-chain-v3',
 'Applying (s,S) replenishment policy with demand-sensing inputs across 12 SKUs yields a projected 21.4% working capital reduction (exceeds 18% target). Reorder points reduced by 8–23% per SKU through improved forecast accuracy. Safety stock recalculated using Poisson demand model at 99.2% fill rate. Phased implementation: 4 SKUs in Month 1 (quick wins, low forecast volatility), 8 SKUs in Months 2–3.',
 0.044, 0.937, 4102, 521, 934, NOW() - INTERVAL '3 days'),

-- ── FINANCIAL RISK (6 queries) ───────────────────────────────────────────────
('sess-fr-002',
 'Generate our Basel IV standardised approach capital requirements for the corporate lending portfolio as at 30 June, including the output floor comparison to the internal model result.',
 'DOMAIN','regulatory',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 'Standardised Approach RWA for corporate portfolio: £14.8Bn. Output floor (72.5% of internal model RWA) binding constraint at £13.4Bn vs internal model £11.2Bn — floor adds £2.2Bn RWA uplift and £176M additional CET1 capital requirement. Top 5 obligor concentrations flagged for large exposure limits review. PRA submission template populated; sign-off required from Chief Risk Officer by 15 July.',
 0.022, 0.974, 3412, 445, 789, NOW() - INTERVAL '30 days'),

('sess-fr-002',
 'Flag all transactions in the past 30 days that exhibit characteristics consistent with trade-based money laundering, specifically over-invoicing patterns in cross-border goods transactions above £500K.',
 'DOMAIN','detection',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 '23 transactions identified meeting TBML over-invoicing criteria. 8 high-priority alerts: consistent invoice-to-market-price ratios exceeding 240% for commodity goods (electronics, textiles) transacted via 4 corporate entities in UAE, Hong Kong and Cyprus. Recommended SAR filings for 8 entities. 15 medium-priority alerts pended for analyst review. MLRO notification generated.',
 0.019, 0.981, 4287, 534, 912, NOW() - INTERVAL '22 days'),

('sess-fr-002',
 'Run a severe but plausible stress test scenario: GDP contracts 4.8%, unemployment rises to 9.2%, house prices fall 28%. What is the projected PD uplift and loan loss provision impact?',
 'DOMAIN','stress_test',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 'Under SBP scenario: retail mortgage PD increases from 1.2% to 4.7% (3.5pp uplift); unsecured consumer PD from 3.8% to 9.1%; SME commercial from 2.4% to 7.3%. Stage 3 loan loss provisions increase by £1.84Bn (from £620M to £2.46Bn). CET1 ratio falls from 14.2% to 11.8% — remains above 10.5% regulatory minimum. Management actions available to preserve 80bps CET1 detailed in Appendix C.',
 0.027, 0.968, 5124, 612, 1047, NOW() - INTERVAL '15 days'),

('sess-fr-002',
 'What are our top 5 counterparty credit exposures to European banks, and how does our current CVA hedge portfolio perform under a 200bp credit spread widening scenario?',
 'DOMAIN','risk_assessment',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 'Top 5 bank counterparty exposures (post netting): Deutsche Bank £2.1Bn, BNP Paribas £1.8Bn, Société Générale £1.4Bn, ING Group £1.1Bn, UniCredit £0.9Bn. Under 200bp spread widening, CVA P&L impact: -£87M. Current CDS hedge covers 62% of exposure. Unhedged residual CVA charge: £33M. Recommend extending hedge to ING (currently unhedged) to reduce residual by £14M.',
 0.024, 0.972, 3687, 478, 834, NOW() - INTERVAL '8 days'),

('sess-fr-002',
 'Prepare the quarterly ICAAP narrative section on credit concentration risk, including Herfindahl-Hirschman Index by sector, geographic concentration and single-name limits compliance.',
 'DOMAIN','reporting',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 'ICAAP Section 4.3 drafted. Portfolio HHI by sector: Real Estate 0.142 (moderate concentration), Financial Services 0.118, Healthcare 0.089 (below concern threshold). Geographic HHI: UK 0.387 (high—home market), Western Europe 0.201, North America 0.134. Single-name limit breaches: 2 exposures (Argent Properties plc at 108% limit, Nexus Financial at 103% limit). Board notification required per ICAAP policy.',
 0.031, 0.963, 4218, 556, 978, NOW() - INTERVAL '4 days'),

('sess-fr-002',
 'Identify model risk exposures in our IRB credit risk models where performance has degraded more than 15% against validation benchmarks, and recommend validation actions.',
 'DOMAIN','model_governance',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-financial-risk-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-financial-risk-v2',
 '4 models flagged with >15% performance degradation: Retail Mortgage PD Model v7.2 (Gini 0.61 vs 0.73 benchmark, -16.4%), SME Scorecard v3.1 (Gini 0.54 vs 0.67, -19.4%), LGD Residential v5 (RMSE +22% vs baseline), CCF Corporate v2 (Spearman -18%). Recommended actions: Mortgage and SME models require immediate redevelopment (MRM Red status); LGD and CCF require enhanced monitoring and recalibration within 90 days.',
 0.029, 0.967, 3891, 501, 867, NOW() - INTERVAL '1 day'),

-- ── CUSTOMER EXPERIENCE (6 queries) ─────────────────────────────────────────
('sess-cx-003',
 'Which customer segments have the highest 90-day churn probability, and what are the top 5 intervention actions ranked by expected retention uplift per £ of cost?',
 'DOMAIN','analysis',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'Highest churn risk segments: Mass Affluent (30-45, mortgage <5yr, 2+ products): 23.4% 90-day churn probability; Young Professionals (digital-only, no savings product): 31.2%; Near-Retirement Downgraders (60-65, declining balance): 18.7%. Top 5 interventions: (1) Proactive rate review call—£12 cost/customer, £340 CLV retention value; (2) Mortgage switch offer; (3) ISA incentive; (4) Financial health check; (5) Fee waiver. Expected portfolio retention uplift: £14.2M annually.',
 0.047, 0.934, 3241, 423, 712, NOW() - INTERVAL '25 days'),

('sess-cx-003',
 'What are the primary drivers of NPS detractor scores among SME customers who have been with us for more than 3 years, and how do they differ from retail customer detractors?',
 'DOMAIN','root_cause',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2","gemma3"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'SME detractor primary drivers: Relationship Manager accessibility (38% of detractor verbatims), online business banking UX (29%), credit decision turnaround time (21%), fee complexity (12%). Retail detractor drivers differ significantly: branch closure proximity (44%), mobile app reliability (31%), fraud dispute resolution time (25%). SME NPS -12 vs retail NPS +8. Recommended: dedicated SME service portal and 4h credit decisions for <£250K facilities.',
 0.052, 0.928, 2987, 387, 654, NOW() - INTERVAL '18 days'),

('sess-cx-003',
 'Build a personalised product recommendation for customer segment "Digital Savers 25-35" that maximises 12-month revenue per customer while staying within FCA Consumer Duty suitability constraints.',
 'DOMAIN','recommendation',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'Digital Savers 25-35 (n=142,000): Recommended product bundle—Lifetime ISA (suitability: 91% eligible, £1,000 bonus incentive), Regular Saver (4.5% rate, cross-sell conversion 34%), Green Mortgage pre-approval (62% homeownership intent). Consumer Duty suitability review: ISA recommended only for under-40s with 5yr+ horizon (confirmed). Projected 12m incremental revenue: £18.4M. Exclusions: 8,200 customers with existing similar products (no-contact flagged).',
 0.043, 0.941, 3587, 456, 789, NOW() - INTERVAL '12 days'),

('sess-cx-003',
 'Analyse the omnichannel customer journey for mortgage applications and identify where the highest proportion of abandonment occurs, with root cause hypotheses.',
 'DOMAIN','journey_analysis',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'Mortgage application funnel: Start 100% → Eligibility check 87% → Document upload 71% → Credit search consent 58% → Decision in principle 44% → Full application 31% → Completion 28%. Highest abandonment: Credit search consent step (-13pp). Root cause hypotheses: (1) Lack of transparency on hard vs soft search; (2) GDPR consent language complexity; (3) 72-hour DIP delay perception. A/B test recommendations: simplified consent explainer (+estimated 4pp conversion).',
 0.049, 0.932, 2748, 356, 612, NOW() - INTERVAL '7 days'),

('sess-cx-003',
 'What is the estimated lifetime value of customers acquired through the Q1 digital marketing campaign vs the branch referral programme, net of acquisition cost?',
 'DOMAIN','attribution',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'Q1 digital campaign (n=18,400 acquisitions): avg CAC £87, projected 5yr CLV £1,240, net CLV £1,153. Branch referral (n=4,200 acquisitions): avg CAC £312, projected 5yr CLV £2,890, net CLV £2,578. Branch referral delivers 2.2× higher net CLV driven by higher initial balance (£24K avg vs £6K digital). However digital channel 4.4× scale advantage. Blended portfolio optimisation: increase digital spend by £2.1M, maintain branch referral programme with relationship manager incentive structure.',
 0.056, 0.921, 3124, 412, 698, NOW() - INTERVAL '3 days'),

('sess-cx-003',
 'Generate the monthly exec dashboard summary for customer experience KPIs: NPS, churn rate, CLV cohort performance, digital adoption and complaint volumes.',
 'DOMAIN','reporting',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cx-analytics-v2"]}'::jsonb,
 'dhs-slm-cx-analytics-v2',
 'June CX Dashboard: NPS +14 (↑3pp MoM, target +12 ✓). Retail 30-day churn 1.8% (↓0.2pp, target <2% ✓). Avg 5yr CLV £2,140 across all cohorts (↑£87 YoY). Digital adoption 74.3% (↑1.8pp, target 76% by Q4—on track). Complaint volumes: 4,280 (↓8% MoM, FCA reportable 142, deadline compliance 97.8%). Key risk: SME NPS remains -12, drag on composite score. Escalation to Product Committee recommended.',
 0.038, 0.953, 2341, 312, 534, NOW() - INTERVAL '1 day'),

-- ── HR & WORKFORCE (4 queries) ───────────────────────────────────────────────
('sess-hr-004',
 'Which business-critical roles have both high vacancy risk and low internal succession pipeline depth, and what targeted interventions should we prioritise in the next 6 months?',
 'DOMAIN','analysis',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-hr-workforce-v1"]}'::jsonb,
 'dhs-slm-hr-workforce-v1',
 '14 roles flagged as critical and succession-deficient. Highest risk cluster: Data Science & AI Engineering (8 roles, avg succession depth 0.8 successors/role, external market salary premium +34%), Regulatory Affairs (3 roles, succession 1.1, critical compliance dependency), Enterprise Architecture (3 roles, succession 0.6). Recommended interventions: targeted fast-track programme for 22 high-potential employees, 3 strategic hires approved via exception budget, external development partnership with Henley Business School.',
 0.058, 0.921, 3124, 401, 678, NOW() - INTERVAL '20 days'),

('sess-hr-004',
 'Analyse voluntary attrition patterns for the Technology division over the last 18 months and identify the key predictive factors. What is the cost of attrition to the business?',
 'DOMAIN','root_cause',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-hr-workforce-v1","llama3:8b"]}'::jsonb,
 'dhs-slm-hr-workforce-v1',
 'Technology division voluntary attrition: 22.4% (18-month rolling, vs 11.2% group average). Top predictive factors: (1) Time-in-role >24 months without promotion (2.8× attrition multiplier); (2) Manager effectiveness score <3.5/5 (2.1×); (3) No L&D activity in 12 months (1.9×); (4) Below-market comp band positioning (1.7×). Total attrition cost: £8.4M/year (recruitment £4.1M, productivity loss £3.2M, knowledge transfer £1.1M). Recommended investment in retention: £2.1M (targeted comp review + L&D), projected 35% attrition reduction = £2.9M net saving.',
 0.064, 0.912, 4218, 534, 891, NOW() - INTERVAL '10 days'),

('sess-hr-004',
 'Generate the Q2 DEI equity audit report covering gender pay gap, ethnic minority representation at Band D and above, disability disclosure rates, and promotion equity ratios.',
 'DOMAIN','reporting',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-hr-workforce-v1"]}'::jsonb,
 'dhs-slm-hr-workforce-v1',
 'Q2 DEI Audit: Gender pay gap (median) 11.8% (↓1.2pp YoY, FTSE 100 benchmark 14.1% — outperforming). Ethnic minority representation Band D+: 12.4% (↑0.8pp, target 17% by 2027 — lagging). Disability disclosure rate: 4.2% (UK estimated prevalence 14% — significant under-reporting, communications campaign recommended). Promotion equity ratio: Female 0.89 (below 1.0 parity), Ethnic minority 0.76 (significant gap, promotion panel review required). Board action items attached.',
 0.049, 0.933, 2987, 378, 641, NOW() - INTERVAL '5 days'),

('sess-hr-004',
 'Build a 3-year workforce capacity plan for the Transformation Programme, accounting for the planned headcount growth of 400 FTEs, skills requirements for the AI platform rollout, and current internal redeployment opportunities.',
 'DOMAIN','planning',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-hr-workforce-v1","llama3:8b"]}'::jsonb,
 'dhs-slm-hr-workforce-v1',
 '3yr Workforce Plan: Year 1—net 180 FTE growth (120 external hire, 60 internal redeployment); Year 2—150 FTE (90 hire, 60 redeploy); Year 3—70 FTE (organic). AI platform roles: 45 ML Engineers, 30 Data Engineers, 18 AI Product Managers—12 internal candidates identified via skills assessment, 81 external hires required. Total programme cost £28.4M over 3 years. Redeployment opportunities: 127 employees in transition roles matched to 3 upskilling pathways (Cloud, Data, Agile). Critical path: ML Engineering ramp starts Q2 Year 1.',
 0.062, 0.918, 5124, 647, 1089, NOW() - INTERVAL '2 days'),

-- ── CYBERSECURITY (4 queries) ────────────────────────────────────────────────
('sess-it-005',
 'Our SIEM has flagged a spike in lateral movement patterns from a compromised endpoint in the Finance department. Generate a full incident response playbook for this threat vector.',
 'DOMAIN','incident_response',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-cybersecurity-v2"]}'::jsonb,
 'dhs-slm-cybersecurity-v2',
 'Incident Response Playbook — Lateral Movement (Finance Endpoint): Phase 1 Containment (0-2hrs): Isolate endpoint FIN-WKS-0847 from network; revoke AD credentials for associated user account; block C2 IPs detected (185.220.x.x range) at perimeter. Phase 2 Investigation (2-24hrs): Memory forensics via Velociraptor; SIEM correlation for 7-day lookback; identify blast radius — 3 file shares accessed, 1 privileged account queried. Phase 3 Eradication: rebuild endpoint from golden image; rotate all Finance division passwords. Phase 4 Lessons Learned: 48hr PIR, CISO notification, ICO assessment (no PII confirmed exfiltrated).',
 0.034, 0.958, 4512, 567, 984, NOW() - INTERVAL '15 days'),

('sess-it-005',
 'Assess our cloud migration risk posture for the remaining 47 on-premise applications scheduled to move to AWS in Q4. Identify the top 10 highest-risk migrations and recommend sequencing.',
 'DOMAIN','risk_assessment',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cybersecurity-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-cybersecurity-v2',
 'Cloud Migration Risk Assessment (47 apps): 8 High Risk, 22 Medium, 17 Low. Top 3 highest risk: (1) CorePayments v2 — SWIFT connectivity, PCI-DSS scope, 6-month cutover minimum; (2) RegulatoryReporting v4 — real-time PRA feeds, data residency requirement; (3) HR-Core — 62,000 employee PII, GDPR Article 46 transfer mechanism needed. Recommended sequencing: low-risk dev/test environments first (Q4), medium-risk internal apps (Q1 next), high-risk deferred to specialist workstream with CTO sign-off.',
 0.041, 0.947, 3891, 489, 823, NOW() - INTERVAL '8 days'),

('sess-it-005',
 'Generate a zero-trust network access policy for third-party contractors accessing our core banking systems, compliant with NCSC Cyber Essentials Plus and PRA operational resilience requirements.',
 'DOMAIN','policy',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-cybersecurity-v2"]}'::jsonb,
 'dhs-slm-cybersecurity-v2',
 'Zero-Trust Contractor Access Policy v1.4: Authentication — MFA mandatory (FIDO2 hardware token for privileged access); conditional access requiring managed device with CrowdStrike agent active; just-in-time access with max 8hr session windows. Network — contractor traffic via isolated VLAN, no direct lateral connectivity to production; all sessions recorded via BeyondTrust PAM. Monitoring — real-time DLP on all file transfers; UEBA baseline established per contractor engagement. NCSC CE+ aligned; PRA operational resilience self-assessment updated. Policy owner: CISO. Review cycle: 6 months.',
 0.029, 0.963, 3287, 423, 712, NOW() - INTERVAL '3 days'),

('sess-it-005',
 'What is our current ITIL problem management backlog status, and for the 8 major incidents in the last quarter, have all root cause analyses been completed and corrective actions closed?',
 'DOMAIN','service_management',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-cybersecurity-v2"]}'::jsonb,
 'dhs-slm-cybersecurity-v2',
 'Problem Management Backlog: 47 open problem records (23 Known Errors, 24 Under Investigation). 8 Major Incidents Q2: 7 RCAs completed (87.5%), 1 overdue (P1-2024-0041: Core Banking outage 4h, RCA 12 days overdue — escalated to Head of Service). Corrective Actions: 31 raised from 7 completed RCAs; 18 closed, 9 in progress, 4 not started. 2 recurring problem patterns identified: network switch firmware and certificate expiry management — both with approved workarounds pending permanent fixes in Q3 release.',
 0.036, 0.951, 2748, 356, 612, NOW() - INTERVAL '1 day'),

-- ── ESG (4 queries) ──────────────────────────────────────────────────────────
('sess-esg-007',
 'Calculate our total Scope 3 Category 1 (purchased goods and services) emissions for FY2024 using spend-based methodology, and identify the top 20 supplier categories driving the highest emissions.',
 'DOMAIN','calculation',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-esg-v2"]}'::jsonb,
 'dhs-slm-esg-v2',
 'Scope 3 Category 1 FY2024: 487,200 tCO2e (spend-based, using EXIOBASE emission factors). Top 5 supplier categories: Steel & Metals manufacturing 112,400 tCO2e (23.1%), Chemical inputs 89,300 tCO2e (18.3%), Road freight 67,800 tCO2e (13.9%), IT hardware procurement 54,200 tCO2e (11.1%), Packaging materials 38,700 tCO2e (7.9%). Total top 20 = 93% of Category 1. Highest decarbonisation leverage: steel supply chain (SBTi-aligned supplier engagement programme recommended — 3 key suppliers have no net-zero commitment).',
 0.038, 0.949, 3891, 489, 823, NOW() - INTERVAL '12 days'),

('sess-esg-007',
 'Model our net-zero pathway to 2050 under the IEA NZE2050 scenario for Scope 1 and 2. What intermediate milestones do we need to hit by 2030 and 2040?',
 'DOMAIN','modelling',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-esg-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-esg-v2',
 'Net-Zero Pathway (IEA NZE2050 aligned): Baseline FY2024 Scope 1+2: 124,300 tCO2e. 2030 target: 62,150 tCO2e (50% reduction). Required actions by 2030: 100% renewable electricity procurement (PPA signed for 78MW — covers 62% of current demand; additional 45MW tender underway), natural gas boiler replacement programme (14 sites, £34M capex), electric fleet transition (380 vehicles). 2040 target: 12,430 tCO2e (90% reduction). 2050: Net Zero via residual removal credits (Woodland Carbon Code, max 5% offset per SBTI criteria). Total capex 2024-2030: £87M.',
 0.041, 0.944, 4512, 567, 987, NOW() - INTERVAL '7 days'),

('sess-esg-007',
 'Score our top 50 suppliers on ESG criteria for inclusion in the Annual Supplier Sustainability Report, flagging any suppliers where we have contractual ESG covenants at risk of breach.',
 'DOMAIN','scoring',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-esg-v2"]}'::jsonb,
 'dhs-slm-esg-v2',
 'Top 50 Supplier ESG Scores (0-100): 12 Green (score 70+), 28 Amber (40-69), 10 Red (<40). Covenant breach risk: 4 suppliers with contractual ESG clauses below minimum threshold — PrecisionCast Ltd (score 31, human rights audit overdue), FastPack Solutions (score 28, no CDP disclosure), ChemBase Industrial (score 34, REACH violation history), TransRoute Asia (score 29, no ISO 14001). Contractual remedy: 90-day improvement plan under Master Supply Agreement Schedule 7. Escalation to Chief Procurement Officer initiated.',
 0.044, 0.939, 3287, 412, 712, NOW() - INTERVAL '4 days'),

('sess-esg-007',
 'Prepare the TCFD Climate Risk section for the 2024 Annual Report, covering physical risk exposure of our top 5 manufacturing sites and transition risk financial materiality.',
 'DOMAIN','disclosure',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-esg-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-esg-v2',
 'TCFD Section 4 — Climate Risk: Physical Risks — Flood risk analysis (IPCC RCP4.5, 2040 horizon): Site Manchester (high risk, £8.4M estimated asset exposure), Site Rotterdam (high, EU climate adaptation investment flagged), Site Bangalore (medium, monsoon intensification), Site Chicago (low-medium), Site São Paulo (medium). Transition Risks — Carbon pricing scenarios: at £75/tCO2e (2030 UK ETS estimate), Scope 1+2 cost exposure £9.3M/year on current trajectory. Disclosure assessed compliant with TCFD 2021 framework. External assurance by KPMG confirmed.',
 0.036, 0.952, 4891, 612, 1043, NOW() - INTERVAL '2 days'),

-- ── MANUFACTURING (4 queries) ────────────────────────────────────────────────
('sess-mfg-008',
 'Perform a root cause analysis for the Line 7 defect spike on 14 June where tablet coating adhesion failures reached 3.8% — 4× the control limit. Which process parameters are the most likely causes?',
 'DOMAIN','root_cause',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-manufacturing-v3"]}'::jsonb,
 'dhs-slm-manufacturing-v3',
 'Line 7 RCA (14 June coating failure): Fishbone analysis identified 3 primary cause candidates — (1) Coating suspension temperature deviation: 14 June 02:00-06:00 batch temperature 58°C vs 54°C specification (thermocouple TH-L7-04 calibration drift confirmed, CAPA-MFG-2024-0142 raised); (2) Coating pan speed variance +12% vs baseline during night shift; (3) Incoming excipient lot EC-2024-0891 moisture content 4.1% vs 2.5% max specification. Root cause confirmed: thermocouple calibration failure. Corrective action: immediate recalibration + 4-hourly manual checks pending PM sensor replacement.',
 0.024, 0.971, 4218, 534, 912, NOW() - INTERVAL '10 days'),

('sess-mfg-008',
 'Generate the OEE dashboard for all 8 production lines for June. Identify the top 3 availability, performance and quality losses and recommend targeted improvement actions.',
 'DOMAIN','performance_review',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-manufacturing-v3"]}'::jsonb,
 'dhs-slm-manufacturing-v3',
 'June OEE Summary: Line 2 (best) 87.3%, Lines 4&6 81.2-82.1%, Lines 1,3,5 74-78%, Lines 7&8 68.4-71.2% (below 75% target). Top Availability losses: Planned maintenance overruns Line 7 (-8.2% avail), changeover delays Lines 1&3 (-5.4%); Top Performance losses: Speed reduction on coating steps Lines 5-8 (-6.1%), minor stoppages (jams) Lines 2&4 (-3.8%); Top Quality losses: Coating defects Line 7 (-3.8%), weight variation Lines 3&5 (-1.9%). Improvement priority: Line 7 thermocouple programme (approved), Lines 1&3 SMED changeover workshop (target 30% reduction), Lines 5-8 process parameter standardisation.',
 0.021, 0.974, 3124, 398, 678, NOW() - INTERVAL '5 days'),

('sess-mfg-008',
 'A predictive maintenance alert has flagged Fill-Seal Machine FS-03 with elevated vibration signature on bearing assembly B2. What is the predicted time to failure and what is the recommended maintenance action?',
 'DOMAIN','maintenance',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-manufacturing-v3"]}'::jsonb,
 'dhs-slm-manufacturing-v3',
 'FS-03 Bearing B2 Analysis: Current RMS vibration 12.4 mm/s (ISO 10816 Zone C — Unsatisfactory). Trend analysis (14-day): exponential degradation curve. Predicted time to failure (P50): 8.4 days; P90: 5.1 days. Recommended action: Schedule planned replacement within 4 days (next available planned downtime window: 2 July 06:00-10:00). Spare bearing available in stores (Part No. SKF-6308-2RS, Qty: 2). Estimated replacement time: 2.5 hours. Risk of reactive failure: 47min line stoppage, £127K lost production. Cost of planned replacement: £2,400 parts + £1,800 labour.',
 0.019, 0.978, 2748, 356, 598, NOW() - INTERVAL '2 days'),

('sess-mfg-008',
 'Generate the monthly FDA 21 CFR Part 11 compliance summary for batch records processed in June, including any electronic signature exceptions and audit trail gaps.',
 'DOMAIN','compliance',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-manufacturing-v3"]}'::jsonb,
 'dhs-slm-manufacturing-v3',
 'June 21 CFR Part 11 Compliance Summary: 847 batch records processed; 842 fully compliant (99.4%). 5 exceptions: (1) Batch L7-20240614-003 — electronic signature timeout error, re-signed within 15 minutes, deviation report filed; (2-3) Batches L3-20240618-001 and L3-20240618-002 — audit trail gap 23:47-23:52 due to server maintenance window (not compliant, CAPA COMP-2024-0089 raised); (4-5) Two batches with incomplete environmental monitoring data linkage (humidity sensor offline 12 June, manual data bridged and approved by QA). All deviations assessed as minor. Regulatory Affairs notified.',
 0.022, 0.973, 3512, 445, 767, NOW() - INTERVAL '1 day'),

-- ── M&A (4 queries) ──────────────────────────────────────────────────────────
('sess-ma-009',
 'Screen our M&A target universe for companies in the healthcare diagnostics space with revenues between £80M and £300M, EBITDA margins above 18%, and strong IP portfolios. Rank by strategic fit score.',
 'DOMAIN','screening',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-ma-strategy-v1","llama3:8b"]}'::jsonb,
 'dhs-slm-ma-strategy-v1',
 'Healthcare Diagnostics Screen (universe: 247 targets): 12 meet all financial criteria. Top 5 by strategic fit: (1) PathogenIQ Ltd — £142M revenue, 24.3% EBITDA, 47 granted patents, PCR/NGS platform synergy score 91/100; (2) DiagnoSys GmbH — £218M, 21.1% EBITDA, strong EU distribution, integration complexity medium; (3) PrecisionLab Inc — £95M, 26.8% EBITDA, highest IP quality, US cross-sell potential; (4) BioScan UK — £167M, 19.4% EBITDA, NHS framework contract (regulatory moat); (5) ClinPath Analytics — £112M, 18.9% EBITDA, data analytics capabilities highly complementary. Valuation range top 5: 9-14× EBITDA.',
 0.048, 0.934, 4512, 567, 978, NOW() - INTERVAL '8 days'),

('sess-ma-009',
 'Build the synergy case for the proposed acquisition of PathogenIQ Ltd at £1.4Bn enterprise value. Include revenue synergies, cost synergies, integration costs and NPV at 12% discount rate.',
 'DOMAIN','financial_modelling',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-ma-strategy-v1"]}'::jsonb,
 'dhs-slm-ma-strategy-v1',
 'PathogenIQ Synergy Case (£1.4Bn EV, 9.8× LTM EBITDA): Revenue synergies £34M annual (Year 3 run-rate): cross-sell diagnostics to existing 1,200 hospital accounts (£18M), PathogenIQ distribution in APAC via our network (£16M). Cost synergies £22M (Year 2 run-rate): procurement consolidation £8M, shared services £9M, property rationalisation £5M. Integration costs £48M over 24 months (TSA, systems, restructuring). NPV at 12% WACC: £287M (positive). IRR: 17.4%. Deal thesis: strong at current valuation; EV sensitivity analysis — deal dilutive above £1.68Bn. Recommended bid range: £1.35–1.52Bn.',
 0.042, 0.941, 5218, 647, 1123, NOW() - INTERVAL '5 days'),

('sess-ma-009',
 'What are the key integration risks for the PathogenIQ acquisition and how should the 100-day integration plan be structured to protect the PathogenIQ revenue run-rate?',
 'DOMAIN','planning',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-ma-strategy-v1","llama3:8b"]}'::jsonb,
 'dhs-slm-ma-strategy-v1',
 'Integration Risk Register (top 5): (1) Key talent retention — PathogenIQ CEO and 4 senior scientists critical to IP; recommend retention packages and earn-out structure; (2) Customer communication — 3 major NHS accounts have change-of-control notification requirements; proactive engagement from Day 1; (3) IT systems — 18-month ERP integration timeline, interim TSA required; (4) Regulatory: 4 in-flight MHRA device registrations — integration cannot alter legal entity until registrations complete; (5) Culture: PathogenIQ operates startup culture — integration approach must preserve autonomy. 100-day plan: Days 1-30 stabilise/communicate; Days 31-60 quick-win synergies; Days 61-100 integration office stood up, IMO governance live.',
 0.051, 0.928, 4891, 612, 1043, NOW() - INTERVAL '3 days'),

('sess-ma-009',
 'Track the post-merger integration milestones for the completed Nexus Analytics acquisition (closed 8 months ago). Which workstreams are behind schedule and what is the revised synergy timeline?',
 'DOMAIN','tracking',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-ma-strategy-v1"]}'::jsonb,
 'dhs-slm-ma-strategy-v1',
 'Nexus Analytics PMI Status (Month 8 of 24): On Track: HR integration (98% complete), brand migration (100%), product bundling launched. Behind Schedule: IT consolidation (42% vs 65% target — ERP data migration complexity underestimated, 4-month delay; revised completion Month 16); Customer retention (88.3% vs 94% target — 3 enterprise accounts churned post-acquisition). Synergy Realisation: Cost synergies £9.2M realised (84% of Year 1 target £11M — on track net of IT delay). Revenue synergies £2.8M (47% of Year 1 target £6M — lagging, root cause: sales team integration slower than planned). Revised Year 1 total synergy: £12M vs £17M target. Recovery plan required.',
 0.044, 0.937, 3891, 489, 834, NOW() - INTERVAL '1 day'),

-- ── DIGITAL TRANSFORMATION (4 queries) ──────────────────────────────────────
('sess-dt-010',
 'Produce a microservices decomposition plan for the Order Management module of our monolithic ERP. Define bounded contexts, domain events, and the recommended migration sequence using the strangler fig pattern.',
 'DOMAIN','architecture',
 '{"steps":["task_classify","coverage_check","decompose","route","synthesise"],"models_used":["dhs-slm-digital-transform-v2"]}'::jsonb,
 'dhs-slm-digital-transform-v2',
 'Order Management Decomposition: 6 bounded contexts identified — Order Capture, Pricing & Promotions, Inventory Allocation, Fulfilment Orchestration, Returns & Refunds, Order Analytics. 23 domain events mapped (OrderPlaced, InventoryReserved, ShipmentDispatched etc). Strangler Fig sequence: Phase 1 (Months 1-3) — Order Analytics (read-only, lowest risk, enables observability); Phase 2 (4-8) — Order Capture via API facade; Phase 3 (9-14) — Pricing extraction (highest coupling, requires event bus); Phase 4 (15-24) — Fulfilment + Inventory; Phase 5 (24-30) — Returns; Legacy ERP decommission Month 30. Event bus: Apache Kafka on AWS MSK recommended.',
 0.041, 0.943, 4891, 612, 1043, NOW() - INTERVAL '6 days'),

('sess-dt-010',
 'Design the data mesh architecture for the Analytics platform. Identify domain owners, data products, and the federated governance model that meets our GDPR and BCBS 239 obligations.',
 'DOMAIN','architecture',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-digital-transform-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-digital-transform-v2',
 'Data Mesh Architecture: 8 data domains identified — Customer (owner: CDO), Risk & Finance (owner: CFO/CRO), Supply Chain (owner: COO), HR (owner: CHRO), Technology (owner: CTO), ESG (owner: Corp Affairs), Sales & Marketing (owner: CMO), Operations (owner: COO). Data Products: 34 initial products catalogued in DataHub; 12 certified for enterprise consumption. Federated Governance: Central Data Council (CDO chaired), domain data stewards mandatory. GDPR compliance: Personal data products require PIA; consent management API integrated via OneTrust. BCBS 239: 11 critical risk data products under enhanced SLA (99.9% availability, ≤4hr data latency). Implementation roadmap: 18 months to full mesh.',
 0.044, 0.938, 4218, 534, 912, NOW() - INTERVAL '4 days'),

('sess-dt-010',
 'Establish AI model governance framework for the 16 AI/ML models currently in production. Classify risk levels, define approval workflows, and create the model risk register.',
 'DOMAIN','governance',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-digital-transform-v2"]}'::jsonb,
 'dhs-slm-digital-transform-v2',
 'AI Governance Framework: 16 production models classified — 3 High Risk (CLV Churn Model, Credit Risk Scorecard, AML Transaction Monitoring — all requiring CRO/CDO sign-off and biannual external validation), 9 Medium Risk (Marketing Propensity, HR Attrition, Fraud Rule-Engine — annual review cycle, model owner sign-off), 4 Low Risk (internal analytics, no customer-facing decisions). Model Risk Register live in Confluence (16 models, 8 in-flight developments). Approval workflow: Model Development → Internal Validation → Second-Line Risk Review → Sponsor Sign-off → Production (High Risk adds Independent Audit). SS1/23 and EBA Guidelines on ML alignment confirmed.',
 0.038, 0.951, 3587, 456, 789, NOW() - INTERVAL '2 days'),

('sess-dt-010',
 'Quantify our technical debt across the legacy application estate and build a prioritised remediation roadmap that balances risk reduction against delivery capacity constraints.',
 'DOMAIN','analysis',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-digital-transform-v2","llama3:8b"]}'::jsonb,
 'dhs-slm-digital-transform-v2',
 'Technical Debt Analysis: 147 legacy applications assessed. Debt quantified: £41M total remediation cost equivalent (CAST methodology). High severity: 23 apps (£18.4M) including 4 with end-of-life OS/middleware (Windows Server 2012, Java 8), 3 with no documented owner, 2 with known security vulnerabilities. Medium: 67 apps (£16.2M). Low: 57 apps (£6.4M). Prioritised roadmap: Year 1 — eliminate 4 EOL platforms (£3.8M, risk-driven), decommission 12 redundant apps (£2.1M saving). Year 2-3 — modernise top 15 business-critical apps via API strangler. 10-year cost of inaction: £124M (compounding maintenance + risk premium).',
 0.046, 0.934, 4512, 567, 978, NOW() - INTERVAL '1 day'),

-- ── PRODUCT R&D (2 queries) ──────────────────────────────────────────────────
('sess-rd-006',
 'Analyse the patent landscape for solid-state battery technology relevant to our portable device product line. Identify white-space opportunities and the key IP holders we should monitor or partner with.',
 'DOMAIN','analysis',
 '{"steps":["task_classify","route","synthesise"],"models_used":["dhs-slm-product-rd-v1","llama3:8b"]}'::jsonb,
 'dhs-slm-product-rd-v1',
 'Solid-State Battery Patent Landscape (portable devices, 2018-2024): 4,847 patents analysed. Key IP holders: Toyota (847 patents, oxide electrolytes dominant), Samsung SDI (412, sulfide electrolytes), QuantumScape (189, lithium-metal anode — US focus), Solid Power (134). White-space opportunities: (1) Flexible thin-film solid-state cells for wearables — <40 filings globally, no dominant assignee; (2) Low-temperature performance optimisation for cold-chain IoT (<-20°C) — 23 filings, two academic institutions. Recommended strategy: file defensive patents in white-space areas; explore licensing from QuantumScape for portable device segment; approach Solid Power re: co-development JV.',
 0.064, 0.913, 4218, 534, 912, NOW() - INTERVAL '14 days'),

('sess-rd-006',
 'Conduct a stage-gate review for Project Aurora (new consumer health monitoring device). Assess technical readiness, market validation, and go-to-market readiness for Gate 3 approval.',
 'DOMAIN','review',
 '{"steps":["task_classify","coverage_check","route","synthesise"],"models_used":["dhs-slm-product-rd-v1"]}'::jsonb,
 'dhs-slm-product-rd-v1',
 'Project Aurora Gate 3 Review: Technical Readiness — TRL 6 achieved (prototype demonstrated in relevant environment). Regulatory path: CE Mark and FDA 510(k) strategy confirmed; Class II medical device classification. IP: 3 patents filed, 1 provisonal in 2 additional markets. Market Validation: 340-person user study completed (NPS +67, intent to purchase 58% at £249 price point). Competitive differentiation: 4.1× longer battery life vs nearest competitor confirmed in independent lab testing. GTM Readiness: retail partnerships (John Lewis, Boots) term sheet agreed; DTC e-commerce channel ready. Gate 3 Decision: APPROVED with conditions — Manufacturing partner finalisation (due Week 6), CE Mark timeline confirmed by Regulatory Affairs (due Week 4).',
 0.071, 0.907, 3891, 489, 834, NOW() - INTERVAL '4 days')

ON CONFLICT DO NOTHING;
